import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import "./globals.css";
import { Noto_Sans } from "next/font/google";
import { cn } from "@/lib/utils";

const notoSans = Noto_Sans({ variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={cn("font-sans", notoSans.variable)}>
      <body className="antialiased">
        <main>{children}</main>
      </body>
    </html>
  );
}
